name: CI

on:
  push:
    branches:
      main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  php-tests:
    name: PHP ${{ matrix.php }} Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          coverage: xdebug

      - name: Install Composer Dependencies
        uses: ramsey/composer-install@v3

      - name: Install Node + PNPM
        uses: ./.github/actions/install-js

      - name: Run PHPStan Tests
        run: pnpm run analyse

      - name: Setup and Start wp-env
        uses: godaddy-wordpress/setup-wp-env@v1
        with:
          phpVersion: ${{ matrix.php }}

      - name: Run Pest Tests Against the Unscoped Release
        run: pnpm run test:pest:ci

  e2e-tests:
    name: E2E Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          tools: composer:v2
          coverage: xdebug
          php-version: 8.3

      - name: Install Composer Dependencies
        uses: ramsey/composer-install@v3

      - name: Install Node + PNPM
        uses: ./.github/actions/install-js

      - name: Setup and Start wp-env
        uses: godaddy-wordpress/setup-wp-env@v1

      - name: Install Playwright
        id: install-playwright
        uses: ./.github/actions/playwright

      - name: Debug Playwright Cache
        run: |
          echo "Playwright version – ${{ steps.install-playwright.outputs.version }}"
          echo "Playwright cached – ${{ steps.install-playwright.outputs.cache-hit }}"

      - name: Run Playwright Tests Against the Scoped Release
        run: |
          config/cli/cli.js test:release

      - uses: daun/playwright-report-summary@v3
        if: always()
        with:
          report-file: playwright-results.json

