name: CI

on:
  push:
    branches:
      main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  php-tests:
    name: PHP ${{ matrix.php }} Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        php: [8.2, 8.3]

    steps:
      - uses: actions/checkout@v4

      - name: Run Shared Setup
        uses: ./.github/actions/shared-setup
        with:
          php-version: ${{ matrix.php }}

      - name: Run PHPStan Tests
        run: pnpm run analyse

      - name: Run Pest Tests Against the Unscoped Release
        run: pnpm run test:pest:ci

  e2e-tests:
    needs: php-tests
    name: E2E Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v4

      - name: Run Shared Setup
        uses: ./.github/actions/shared-setup
        with:
          php-version: ${{ matrix.php }}
          playwright: true

      - name: Run Playwright Tests Against the Scoped Release
        run: |
          config/cli/cli.js test:release

      - uses: daun/playwright-report-summary@v3
        if: always()
        with:
          report-file: playwright-results.json

