name: Test GH CLI

on:
  push:
    branches:
      main

permissions:
  contents: write
  pull-requests: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  gh-playground:

    name: Test GH CLI
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true

    steps:
      - name: Configure Git
        run: |
          git config --global user.email "bot@rassohilber.com"
          git config --global user.name "Rasso Hilber's Bot"

      - name: Check out repository
        uses: actions/checkout@v4

      - name: "Get Latest Tag"
        id: latest-tag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: Get latest release tag
        id: get_latest_tag
        run: |
          TAG=$(gh release list --limit 1 --json tagName -q '.[0].tagName')
          echo "LATEST_TAG=$TAG" >> $GITHUB_ENV
          echo "latest tag: $TAG"
        env:
          GH_TOKEN: ${{ github.token }}
